# Etapa 1: Build
FROM node:20 AS builder
WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .

# 👇 IMPORTANTE: declara los ARG
ARG VITE_CLERK_PUBLISHABLE_KEY
ARG VITE_API_URL

# 👇 los pasas también a ENV para que Vite los lea
ENV VITE_CLERK_PUBLISHABLE_KEY=${VITE_CLERK_PUBLISHABLE_KEY}
ENV VITE_API_URL=${VITE_API_URL}

RUN npm run build

# Etapa 2: Nginx
FROM nginx:stable-alpine
COPY --from=builder /app/dist /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
