
services:
  # 🧠 ORQUESTADOR (Node.js)
  orquestador:
    build: ./Backend/MS_Orquestador
    container_name: orquestador
    restart: unless-stopped
    ports:
      - "8081:8081"
    env_file:
      - ./Backend/MS_Orquestador/.env
    depends_on:
      - auth
      - guias
      - reserva
    networks:
      - microservices-net

  # 🔐 AUTH SERVICE (Node.js)
  auth:
    build: ./Backend/MS_Auth
    container_name: auth
    restart: unless-stopped
    ports:
      - "8000:8000"
    env_file:
      - ./Backend/MS_Auth/.env
    networks:
      - microservices-net

  # 📘 GUIAS SERVICE (Spring Boot)
  guias:
    build: ./Backend/MS_Guias
    container_name: guias
    restart: unless-stopped
    ports:
      - "8080:8080"
    env_file:
      - ./Backend/MS_Guias/.env
    networks:
      - microservices-net

  # 📅 RESERVA SERVICE (Node.js)
  reserva:
    build: ./Backend/MS-Reserva
    container_name: reserva
    restart: unless-stopped
    ports:
      - "4000:4000"
    env_file:
      - ./Backend/MS-Reserva/.env
    networks:
      - microservices-net

    # ⚛️ FRONTEND (React + Vite + Tailwind)
  frontend:
    build:
      context: ./Frontend
      dockerfile: Dockerfile
      args:
        VITE_API_URL: http://proyecto-lb-967616209.us-east-1.elb.amazonaws.com
        VITE_CLERK_PUBLISHABLE_KEY: pk_test_c3RpcnJpbmctc3VuYmlyZC03NS5jbGVyay5hY2NvdW50cy5kZXYk
    container_name: frontend
    ports:
      - "80:80"
    depends_on:
      - orquestador
    environment:
      VITE_API_URL: http://proyecto-lb-967616209.us-east-1.elb.amazonaws.com
      VITE_CLERK_PUBLISHABLE_KEY: pk_test_c3RpcnJpbmctc3VuYmlyZC03NS5jbGVyay5hY2NvdW50cy5kZXYk
    networks:
      - microservices-net
    restart: unless-stopped



# 🔗 Red compartida con la infraestructura
networks:
  microservices-net:
    external: true
